### ISSUE TITLE
vs2017 定义char 参数编译错误

### ISSUE THREAD

**Issue by coolxv** [fanchy/fflua#10]
int DrvIntf::combinationKeyDown(int key1, int key2, int key3, int key4, int key5, int key6)
{
	return 0;
}

void reg_drv_intf_lapi(lua_State *ls)
{
	//! 注册基类函数, ctor() 为构造函数的类型  
	fflua_register_t<DrvIntf, ctor()>(ls, "DrvIntf")
		.def(&DrvIntf::combinationKeyDown, "combinationKeyDown");

}

1>------ 已启动全部重新生成: 项目: periphery_c, 配置: Debug x64 ------
1>pch.cpp
1>capture_screen.cpp
1>drv_intf.cpp
1>d:\work\gameperipheries1\fflua\fflua_register.h(1424): error C2664: “int ff::lua_op_t<char>::lua_to_value(lua_State *,int,int8_t &)”: 无法将参数 3 从“ff::basetype_ptr_traits_t<char>::arg_type_t”转换为“int8_t &”
1>d:\work\gameperipheries1\fflua\fflua_register.h(1411): note: 编译 类 模板 成员函数 "int ff::class_function_traits_t<FUNC_TYPE>::lua_function(lua_State *)" 时
1>        with
1>        [
1>            FUNC_TYPE=int (__cdecl DrvIntf::* )(char,char,char,char,char,char)
1>        ]
1>d:\work\gameperipheries1\fflua\fflua_register.h(256): note: 参见对正在编译的函数 模板 实例化“int ff::class_function_traits_t<FUNC_TYPE>::lua_function(lua_State *)”的引用
1>        with
1>        [
1>            FUNC_TYPE=int (__cdecl DrvIntf::* )(char,char,char,char,char,char)
1>        ]
1>d:\work\gameperipheries1\fflua\fflua_register.h(256): note: 参见对正在编译的 类 模板 实例化 "ff::class_function_traits_t<FUNC_TYPE>" 的引用
1>        with
1>        [
1>            FUNC_TYPE=int (__cdecl DrvIntf::* )(char,char,char,char,char,char)
1>        ]
1>d:\work\gameperipheries1\fflua\fflua_register.h(2587): note: 参见对正在编译的函数 模板 实例化“ff::fflua_register_t<DrvIntf,void (void)> &ff::fflua_register_t<DrvIntf,void (void)>::def_class_func<RET(__cdecl DrvIntf::* )(ARG1,ARG2,ARG3,ARG4,ARG5,ARG6)>(FUNC_TYPE,const std::string &)”的引用
1>        with
1>        [
1>            RET=int,
1>            ARG1=char,
1>            ARG2=char,
1>            ARG3=char,
1>            ARG4=char,
1>            ARG5=char,
1>            ARG6=char,
1>            FUNC_TYPE=int (__cdecl DrvIntf::* )(char,char,char,char,char,char)
1>        ]
1>d:\work\gameperipheries1\fflua\fflua_register.h(2587): note: 参见对正在编译的函数 模板 实例化“ff::fflua_register_t<DrvIntf,void (void)> &ff::fflua_register_t<DrvIntf,void (void)>::def_class_func<RET(__cdecl DrvIntf::* )(ARG1,ARG2,ARG3,ARG4,ARG5,ARG6)>(FUNC_TYPE,const std::string &)”的引用
1>        with
1>        [
1>            RET=int,
1>            ARG1=char,
1>            ARG2=char,
1>            ARG3=char,
1>            ARG4=char,
1>            ARG5=char,
1>            ARG6=char,
1>            FUNC_TYPE=int (__cdecl DrvIntf::* )(char,char,char,char,char,char)
1>        ]
1>d:\work\gameperipheries1\fflua\fflua_register.h(250): note: 参见对正在编译的函数 模板 实例化“void ff::fflua_register_router_t<FUNC_TYPE>::call<ff::fflua_register_t<DrvIntf,void (void)>>(REG_TYPE *,RET (__cdecl DrvIntf::* )(ARG1,ARG2,ARG3,ARG4,ARG5,ARG6),const std::string &)”的引用
1>        with
1>        [
1>            FUNC_TYPE=int (__cdecl DrvIntf::* )(char,char,char,char,char,char),
1>            REG_TYPE=ff::fflua_register_t<DrvIntf,void (void)>,
1>            RET=int,
1>            ARG1=char,
1>            ARG2=char,
1>            ARG3=char,
1>            ARG4=char,
1>            ARG5=char,
1>            ARG6=char
1>        ]
1>d:\work\gameperipheries1\fflua\fflua_register.h(250): note: 参见对正在编译的函数 模板 实例化“void ff::fflua_register_router_t<FUNC_TYPE>::call<ff::fflua_register_t<DrvIntf,void (void)>>(REG_TYPE *,RET (__cdecl DrvIntf::* )(ARG1,ARG2,ARG3,ARG4,ARG5,ARG6),const std::string &)”的引用
1>        with
1>        [
1>            FUNC_TYPE=int (__cdecl DrvIntf::* )(char,char,char,char,char,char),
1>            REG_TYPE=ff::fflua_register_t<DrvIntf,void (void)>,
1>            RET=int,
1>            ARG1=char,
1>            ARG2=char,
1>            ARG3=char,
1>            ARG4=char,
1>            ARG5=char,
1>            ARG6=char
1>        ]
1>d:\work\gameperipheries1\peripheries\periphery_c\periphery_c\drv_intf.cpp(171): note: 参见对正在编译的函数 模板 实例化“ff::fflua_register_t<DrvIntf,void (void)> &ff::fflua_register_t<DrvIntf,void (void)>::def<int(__cdecl DrvIntf::* )(char,char,char,char,char,char)>(FUNC_TYPE,const std::string &)”的引用
1>        with
1>        [
1>            FUNC_TYPE=int (__cdecl DrvIntf::* )(char,char,char,char,char,char)
1>        ]
1>d:\work\gameperipheries1\peripheries\periphery_c\periphery_c\drv_intf.cpp(201): note: 参见对正在编译的函数 模板 实例化“ff::fflua_register_t<DrvIntf,void (void)> &ff::fflua_register_t<DrvIntf,void (void)>::def<int(__cdecl DrvIntf::* )(char,char,char,char,char,char)>(FUNC_TYPE,const std::string &)”的引用
1>        with
1>        [
1>            FUNC_TYPE=int (__cdecl DrvIntf::* )(char,char,char,char,char,char)
1>        ]
1>d:\work\gameperipheries1\fflua\fflua_register.h(1425): error C2664: “int ff::lua_op_t<char>::lua_to_value(lua_State *,int,int8_t &)”: 无法将参数 3 从“ff::basetype_ptr_traits_t<char>::arg_type_t”转换为“int8_t &”
1>d:\work\gameperipheries1\fflua\fflua_register.h(1426): error C2664: “int ff::lua_op_t<char>::lua_to_value(lua_State *,int,int8_t &)”: 无法将参数 3 从“ff::basetype_ptr_traits_t<char>::arg_type_t”转换为“int8_t &”
1>d:\work\gameperipheries1\fflua\fflua_register.h(1427): error C2664: “int ff::lua_op_t<char>::lua_to_value(lua_State *,int,int8_t &)”: 无法将参数 3 从“ff::basetype_ptr_traits_t<char>::arg_type_t”转换为“int8_t &”
1>d:\work\gameperipheries1\fflua\fflua_register.h(1428): error C2664: “int ff::lua_op_t<char>::lua_to_value(lua_State *,int,int8_t &)”: 无法将参数 3 从“ff::basetype_ptr_traits_t<char>::arg_type_t”转换为“int8_t &”
1>d:\work\gameperipheries1\fflua\fflua_register.h(1429): error C2664: “int ff::lua_op_t<char>::lua_to_value(lua_State *,int,int8_t &)”: 无法将参数 3 从“ff::basetype_ptr_traits_t<char>::arg_type_t”转换为“int8_t &”
1>periphery_c.cpp
1>正在生成代码...
1>已完成生成项目“periphery_c.vcxproj”的操作 - 失败。
========== 全部重新生成: 成功 0 个，失败 1 个，跳过 0 个 ==========

**Comment by fanchy** [comment]
fixed
