### ISSUE TITLE
指针类型的返回值为NULL时好像有点问题

### ISSUE THREAD

**Issue by aa851853** [fanchy/fflua#12]
fflua_type.h

template<typename T>
struct lua_op_t<T*>
{
static void push_stack(lua_State* ls_, T* arg_)

arg_为NULL这种情况好像没有考虑

我暂时这样处理
if (arg_ == NULL)
{
	lua_pushnil(ls_);
	return;
}

**Comment by fanchy** [comment]
嗯，null自动转nil是个思路，但是这样类型信息将会丢失，目前fflua做了限定不允许lua传空指针给c++。传入null指针到lua需要谨慎一些。
