### ISSUE TITLE
C++ 有多个构造函数的时候如何处理?

### ISSUE THREAD

**Issue by gantleman** [fanchy/fflua#13]

**Comment by fanchy** [comment]
目前fflua还不能支持函数重载，你可以通过factory的方式取巧实现

**Comment by gantleman** [comment]
> 目前fflua还不能支持函数重载，你可以通过factory的方式取巧实现

谢谢您的回复，为了开发工程需要，想把bullet 物理库引入lua。本想取巧把bullet的c++接口导出来使用。重新评估发现bullet本身就不能满足我的需要，需要添加大量的功能才能导出。加上使用的功能只有碰撞和直线测试等两三个。手动写接口也不是很麻烦。引出接口在lua里做bullet wrap工程风险极高。所以评估了所有github上能找到的c++导出lua的方案后果断放弃了。
吐槽下bullet 有2千多个函数，即使用tolua++或者cocos2dx的脚本，写配置文件也得写吐血。并且其中不确定风险极高。
其中还有一个有趣且更极端的项目，将bullet库直接由c++转成了lua。
https://github.com/SwadicalRag/wasm2lua
但我在windows和linux都没编译成功。
从产品角度说fflua，小项目用不上直接写接口就好。
大项目如bullet，2千多个函数无论是转写还是配置，下来也让人崩溃。
