### ISSUE TITLE
run_string 内的异常信息字符串有个英文单词错了faled，小问题

### ISSUE THREAD

**Issue by FettLuo** [fanchy/fflua#4]
顺便说一下，包含文件最好不要相对与lua这个目录，这可能源于你的目录/项目管理习惯，不过这与lua源码里的包含方式不太相同。你一共是三个h文件，这精简的很不错了，要是让用户再去设置一下包含目录就多麻烦了一次。至少我会把你的三个文件放在lua文件一起，或项目一起，不想再设置什么目录了。

**Comment by fanchy** [comment]
这个确实基于我的目录，你说的有道理，别人也反应过这个问题。
