### ISSUE TITLE
int64_t和uint64_t数据丢失

### ISSUE THREAD

**Issue by hlxxiang** [fanchy/fflua#5]
strtoll用 c++11的stoll替换，strtoull用 c++11 的stoull替换

**Comment by fanchy** [comment]
我会测试修改的，最近有点忙，晚一点修复，如果你已经修复了，如果可以的话帮忙贴出修改代码

**Comment by hlxxiang** [comment]
/*
struct strtoll_tool_t
{
    static long do_strtoll(const char* s, const char*, int){
        return atol(s);
    }
};
#define strtoll strtoll_tool_t::do_strtoll
#define strtoull (unsigned long)strtoll_tool_t::do_strtoll
*/
这一段可以注释
        static int get_ret_value(lua_State* ls_, int pos_, int64_t& param_)
    {
        if (!lua_isstring(ls_, pos_))
        {
            return -1;
        }

        size_t len  = 0;
        const char* src = lua_tolstring(ls_, pos_, &len);
        param_ = stoll(src);
        return 0;
    }
    strtoll改为stoll
    static int lua_to_value(lua_State* ls_, int pos_, int64_t& param_)
    {
        size_t len = 0;
        const char* str = luaL_checklstring(ls_, pos_, &len);
        param_ = stoll(str);
        return 0;
    }
    
    static int get_ret_value(lua_State* ls_, int pos_, uint64_t& param_)
    {
        if (!lua_isstring(ls_, pos_))
        {
            return -1;
        }

        size_t len  = 0;
        const char* src = lua_tolstring(ls_, pos_, &len);
        param_ = stoull(src);
        return 0;
    }

    static int lua_to_value(lua_State* ls_, int pos_, uint64_t& param_)
    {
        size_t len = 0;
        const char* str = luaL_checklstring(ls_, pos_, &len);
        param_ = stoull(str);
        return 0;
    }
    strtoull改为stoull

**Comment by fanchy** [comment]
fixed
